### ISSUE TITLE
devops setup crashes

### ISSUE THREAD

**Issue by shiruken1** [stphivos/django-angular2-fullstack-compact#4]
Hey there!

When I run ./devops setup, I see this message

```
Successfully added box 'trusty64' with provider 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* The following settings shouldn't exist: env
```

Any ideas?

Thanks for this awesome repo. Looking forward to contributing :smile:

**Comment by shiruken1** [comment]
Well nevermind on that. For any future reader: vagrant needs to be at least 1.8 (also, the hashbang line in devops needs to be changed to #!/bin/bash if you're on Ubuntu)

**Comment by shiruken1** [comment]
Now vagrant's reporting not to have vm-install.sh, from the line in Vagrantfile:

```
config.vm.provision "shell", :path => "vm-install.sh"
```

I assume scripts/temp.sh was supposed to be vm-install.sh, so I renamed the script and adjusted the Vagrantfile to match. Now it's installing, but complaining about CHROME_BIN not being set. Testing again with google-chrome-stable added to the apt-get install portion, and the export added to vars

**Comment by shiruken1** [comment]
Saw the latest update and merged them in, but I keep running into (what I believe is) this [issue](https://github.com/mitchellh/vagrant/issues/1303) 

If I run vagrant ssh afterwards, the repo is all there with the latest commit, but the setup script always crashes reporting:

```
==> default: Clone git repo
==> default: # github.com SSH-2.0-libssh-0.7.0
==> default: # github.com SSH-2.0-libssh-0.7.0
==> default: no hostkey alg
==> default: Cloning into 'app'...
==> default: Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
==> default: Permission denied (publickey).
==> default: fatal: Could not read from remote repository.
==> default: 
==> default: Please make sure you have the correct access rights
==> default: and the repository exists.
```

Any clue as to what I should do?

Thanks again!

**Comment by stphivos** [comment]
Hello!

Thanks for the feedback and for bringing up these issues. I set-up a new Ubuntu desktop machine to test everything once again because my host is running os x and I pushed some changes incompatible with linux. (i.e. mac doesn’t use the gnu grep, default shell for system on ubuntu is dash etc.)

So the shebang line is fixed now and I will update the readme to include the minimum versions of all the requirements.

About `temp.sh` I’ve been meaning to remove it since that was what I used before ansible and I wanted to convert everything to roles.

For this last issue `Permission denied (publickey)` have you tried the following:
- Adding your ssh key to the ssh-agent: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent
- Adding your ssh key to your github account: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/#platform-linux

You can test it’s setup properly with these steps: https://help.github.com/articles/testing-your-ssh-connection/#platform-linux

Hope this helps! :)

**Comment by shiruken1** [comment]
Hello again, and thank you for the pointers. Unfortunately, the ssh test (ssh -T git@github.com) passes, so I don't believe it's related. However, one thing I did notice from the vagrant.sh script was that the repo is supposed to be cloned at /${SERVER_ROOT_NAME}/${APPLICATION_NAME}, but in my install, it ended up directly in /home/vagrant.

I went ahead and fired up the frontend w/o issues, but when I run "manage.py runserver" I keep getting "django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty." despite the key being in backend/settings/base.py, and I even copied it to prod, local and dev to no avail :disappointed:

**Comment by stphivos** [comment]
It always exists in `/home/vagrant` because of this line in `Vagrantfile`:

``` ruby
config.vm.synced_folder ".", "/home/vagrant/#{ENV['APPLICATION_NAME']}"
```

The deployment location used by ansible is `/${SERVER_ROOT_NAME}/${APPLICATION_NAME}` which defaults to `/webapps/fullstack`. So the vbox will have both, but `/home/vagrant` is the one that gets synced to your host machine that you can use for development with your full desktop tools.

Another thing to double check for the permission error is whether you have updated the `vars` file to use your github fork that is the one that knows your ssh keys:

``` bash
export GIT_REPO=git@github.com:shiruken1/django-angular2-fullstack-devops.git
```

**Comment by shiruken1** [comment]
Ah, gotcha. First time working with Vagrant. My apologies! I'm used to setting up everything locally.

And, yeah, I had changed the var to my fork of the repo prior to running setup.

**Comment by stphivos** [comment]
Hey, any luck with these issues? Feel free to share your settings and I can clone your fork and try to replicate.

**Comment by stphivos** [comment]
Closing this for now, let's re-visit if needed.
